// <auto-generated/>
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppression either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~M:Vasont.IdentityServer.Backchannel.IdentityClient.AuthenticateAsync(System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1054:Uri parameters should not be strings", Justification = "<Pending>", Scope = "member", Target = "~M:Vasont.IdentityServer.Backchannel.IdentityClient.RequestClientCredentials(System.String,System.String,System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task{IdentityModel.Client.TokenResponse}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "False positive. This must serialize.", Scope = "member", Target = "~P:Vasont.IdentityServer.Backchannel.Models.BackchannelUserModel.Organizations")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:Vasont.IdentityServer.Backchannel.Models.BackchannelSubscriptionModel.Settings")]
